name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.kt'
      - '.github/workflows/android-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.py'
      - '.github/workflows/android-ci.yml'

permissions:
  contents: read

jobs:
  android-unit-tests:
    name: Android Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Ensure the Gradle wrapper is executable
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Run unit tests
      - name: Run Android tests
        run: ./gradlew test
