name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.kt'
      - '.github/workflows/android-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.py'
      - '.github/workflows/android-ci.yml'

permissions:
  contents: read

jobs:
  android-tests:
    name: Android Unit & Instrumentation Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - uses: actions/checkout@v3

      # Set up JDK (required for Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Cache Gradle artifacts
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Run JVM unit tests
      - name: Run unit tests
        run: ./gradlew test --no-daemon

      # Run intrumentation tests
      - name: Run instrumentation tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35              
          target: google_apis         
          arch: x86_64               
          emulator-options: -no-window -gpu swiftshader_indirect
          script: ./gradlew connectedAndroidTest --no-daemon