name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.kt'
      - '.github/workflows/android-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.kt'
      - '.github/workflows/android-ci.yml'

permissions:
  contents: read

jobs:
  android-tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        working-directory: ./Application
        run: chmod +x gradlew
      
      - name: Run unit tests
        working-directory: ./Application
        run: ./gradlew test
      
