name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        build_type: [ Debug, Release ]

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure, build & test
        # Everything below runs from your Motor_controller directory
        working-directory: Embedded/Arduino/Motor_controller
        run: |
          # select compiler
          export CXX=${{ matrix.compiler }}++
          # configure into a build/ subfolder
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          # compile
          cmake --build build -- -j$(nproc)
          # run your GoogleTest suite
          ctest --output-on-failure --test-dir build
