name: Python CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/python-ci.yml'

permissions:
  contents: read

jobs:
  pytest-api-testing:
    name: Pytest API Testing
    runs-on: ubuntu-latest

    steps:
      # 1) Grab the code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # 3) Cache pip install
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) Installerar dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Kör testerna
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
