name: ServerJS CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Application/Server/**'
      - '.github/workflows/serverjs-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'Application/Server/**'
      - '.github/workflows/serverjs-ci.yml'

permissions:
  contents: read

jobs:
  js-api-testing:
    name: ServerJS Run Automated Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies in Application/Server
      - name: Install dependencies
        working-directory: Application/Server
        run: npm install

      # 4. Run your JS tests
      - name: Run npm test
        working-directory: Application/Server
        run: npm test