name: Python CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.py'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.py'
      - '.github/workflows/python-ci.yml'

permissions:
  contents: read

jobs:
  pytest-api-testing:
    name: Pytest API Testing
    runs-on: ubuntu-latest

    steps:
      # Hämtar koden
      - uses: actions/checkout@v3

      # Sätter upp Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Installerar pytest
      - name: Install pytest
        run: pip install pytest

      # Sätter PYTHONPATH till Embedded så RaspberryPI-importen fungerar
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/Embedded" >> $GITHUB_ENV

      # Kör testerna
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q